### PR TITLE
macos build

### PR DESCRIPTION
**Pull request by Sophrinix**
Amazing job. Here is a small update to run this on macOS.
Thank you for doing this project. It is really eye opening.

### CODE REVIEW

**Comment by Lumorti** [comment]
Seems good, just one question, shouldn't there be some install instructions for sdl using brew as well as OpenMP? Like "brew install sdl2" or something? I don't know mac at all so forgive me if I'm misunderstanding

**Comment by Sophrinix** [comment]
That is very fair. I'll make sure that is the package in brew and add that.

**Comment by Sophrinix** [comment]
updated readme to include brew install libomp sdl2

**Comment by Lumorti** [comment]
Wonderful, looks good!

**Pull request merged**
